name: Build CI Wheels

on:
  push:
    branches:
      - main
    tags: 'yt_astro_analysis-*'
  pull_request:
     paths:
       - .github/workflows/wheels.yaml
  workflow_dispatch:

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          windows-2019,
          macos-12,
        ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels for CPython
        uses: pypa/cibuildwheel@v2.22.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux_*"  #  numpy doesn't have wheels for musllinux so we can't build some quickly and without bloating
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_ARCHS_WINDOWS: "auto64"
          CIBW_ENVIRONMENT: "LDFLAGS='-static-libstdc++'"
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'yt_astro_analysis-'
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/yt_astro_analysis-')
    environment:
      name: upload_pypi
      url: https://pypi.org/p/yt-astro-analysis
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tarball
          path: dist

      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@v1.12.2
